linters-settings:
  govet:
    shadow: true
  golint:
    min-confidence: 0.6
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - hugeParam
      - rangeValCopy

linters:
  disable-all: true
  enable:
    - revive
    - govet
    - unconvert
    - gosec
    - misspell
    - unused
    - typecheck
    - ineffassign
    - stylecheck
    - gochecknoinits
    - gocritic
    - nakedret
    - gosimple
    - prealloc

  fast: false


run:
  #  modules-download-mode: vendor

  concurrency: 4

issues:
  exclude-dirs:
    - vendor
  exclude-rules:
    - text: "should have a package comment, unless it's in another file for this package"
      linters:
        - golint
    - text: "exitAfterDefer:"
      linters:
        - gocritic
    - text: "whyNoLint: include an explanation for nolint directive"
      linters:
        - gocritic
    - text: "go.mongodb.org/mongo-driver/bson/primitive.E"
      linters:
        - govet
    - text: "weak cryptographic primitive"
      linters:
        - gosec
    - text: "at least one file in a package should have a package comment"
      linters:
        - stylecheck
    - text: "package-comments: should have a package comment"
      linters:
        - revive
    - text: 'Deferring unsafe method "Close" on type "io.ReadCloser"'
      linters:
        - gosec
    - linters:
        - unparam
        - unused
        - revive
      path: _test\.go$
      text: "unused-parameter"
    # Exclude all gosec issues for test files
    - path: "_test.go"
      linters:
        - gosec
    # Exclude specific gosec issues in main code
    - text: "G304: Potential file inclusion via variable"
      linters:
        - gosec
  exclude-use-default: false
