linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - hugeParam
      - rangeValCopy

linters:
  disable-all: true
  enable:
    - revive
    - govet
    - unconvert
    - gosec
    - misspell
    - unused
    - typecheck
    - ineffassign
    - stylecheck
    - gochecknoinits
    - gocritic
    - nakedret
    - gosimple
    - prealloc
    - usetesting
    - testifylint
    - nonamedreturns
  fast: false

run:
  concurrency: 4

issues:
  exclude-dirs:
    - vendor
  exclude-rules:
    - text: "should have a package comment, unless it's in another file for this package"
      linters:
        - revive
    - text: "exitAfterDefer:"
      linters:
        - gocritic
    - text: "whyNoLint: include an explanation for nolint directive"
      linters:
        - gocritic
    - text: "go.mongodb.org/mongo-driver/bson/primitive.E"
      linters:
        - govet
    - text: "weak cryptographic primitive"
      linters:
        - gosec
    - text: "at least one file in a package should have a package comment"
      linters:
        - stylecheck
    - text: "package-comments: should have a package comment"
      linters:
        - revive
    - text: 'Deferring unsafe method "Close" on type "io.ReadCloser"'
      linters:
        - gosec
    - linters:
        - unparam
        - unused
        - revive
      path: _test\.go$
    - text: "Potential file inclusion via variable"
      linters:
        - gosec
      path: _test\.go$
    - text: "should have a package comment"
      linters:
        - revive
    - text: "Error return value of .+Close. is not checked"
      path: _test\.go$
      linters:
        - errcheck
  exclude-use-default: false