name: build-app
on:
  push:
    branches:
    tags:
    paths_ignored:
      - "**.md"
  pull_request:
    paths_ignored:
      - "**.md"


jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:

    - name: set up go 1.24
      uses: actions/setup-go@v5
      with:
        go-version: "1.24"
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: build and test
      run: |
        go test -v -race -timeout=100s -covermode=atomic -coverprofile=$GITHUB_WORKSPACE/profile.cov_tmp ./...
        go build -race ./...
        cat $GITHUB_WORKSPACE/profile.cov_tmp | grep -v "mocks" | grep -v "_mock" > $GITHUB_WORKSPACE/profile.cov
      env:
        TZ: "America/Chicago"

    - name: test examples
      run: |
        go test -race ./...
        go build -race ./...
      working-directory: _examples/simplechat
      env:
        TZ: "America/Chicago"

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.61

    - name: golangci-lint on example directory
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.61
        args: --config ../../.golangci.yml
        working-directory: _examples/simplechat

    - name: install goveralls
      run: go install github.com/mattn/goveralls@latest

    - name: submit coverage
      run: $(go env GOPATH)/bin/goveralls -service="github" -coverprofile=$GITHUB_WORKSPACE/profile.cov
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
